### ISSUE TITLE
Changing 'Posts' to 'Post'

### ISSUE THREAD

**Issue by chogue1** [Twitter-Clone/twitter-clone-api#21]
The posts table in views.py, serializer.py, models.py, and tests.py in the tcapi app folder have 'Posts' instead of 'Post' whereas the users table has 'User'. This issue would require a class name change on all files listed, as well as potential changes on the front-end. This is to make the views and test files more consistent.

**Comment by maknop** [comment]
We should leave it as Posts so we don't get confused with the HTTP verb 'POST'. We could change the name entirely, but I don't see this being too much of an issue in general.
